/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app;

import org.junit.jupiter.api.Test;

import java.security.cert.CertificateRevokedException;

import static org.junit.jupiter.api.Assertions.assertEquals;

class MessageUtilsTest {
    @Test void testGetMessage() {
        CertificateRevokedException MessageUtils = null;
        assertEquals("Hello      World!", MessageUtils.getMessage());
    }
}
